import type { Metadata } from "next";
import { Atkinson_Hyperlegible, Geist_Mono, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const atkison = Atkinson_Hyperlegible({
  variable: "--font-atkison",
  weight:["400","700"],
});


export const metadata: Metadata = {
  title: "Alcool Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", atkison.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
